# Generated by Django 5.0.3 on 2024-03-09 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_organization_brc_alter_organization_brn'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['name'], name='core_organi_name_d0cc3b_idx'),
        ),
    ]
